### PR TITLE
WIP : Cluster properties

### PR DESCRIPTION
**Pull request by EmyrClement**
Work in progress for adding the cluster properties block to the emulator.

For some reason, my editor doesn't like the formatting of `Stage2.hh`, and introduces many whitespace/formatting standards.  I will try to undo those/separate out into another commit.

### CODE REVIEW

**Comment by indra-ehep** [comment]
The contents of  `CMSSWCode/HLS_arbitrary_Precision_Types/include` are not visible in the Files changed tab. How many files are to be included in this folder ?

**Comment by EmyrClement** [comment]
> The contents of `CMSSWCode/HLS_arbitrary_Precision_Types/include` are not visible in the Files changed tab. How many files are to be included in this folder ?

These are the [HLS datatypes](https://github.com/Xilinx/HLS_arbitrary_Precision_Types), which I tried adding as a submodule, rather than copying the files into this repository, but I don't think that has worked.  I will fix this.

**Comment by indra-ehep** [comment]
Paul has updated "TPGStage2Emulation/Stage2.hh" about 3 hours ago [[link](https://github.com/indra-ehep/hgcal-tpg-fe/commit/b05e138ec6bce32f36267f91e40402714bdb2ed4)] to include the number of trigger cells. Is the Stage2.hh of "clusterProperties" branch updated with that ? Please find the conflicts [here](https://github.com/indra-ehep/hgcal-tpg-fe/pull/38/conflicts).

**Comment by EmyrClement** [comment]
There was still work to be done for this PR - I have just pushed some more changes to my branch.  Can you reopen/undo the merge this PR?

**Pull request merged**
