### PR TITLE
Examples to read/write EMP pattern files using CMSSW tools

### PR DESCRIPTION
**Pull request by EmyrClement**
This PR adds the tools to be able to read/write EMP pattern files using existing tools, and provides an example.

There are some additional dependencies required:
  - HLS arbitrary precision types, included via a submodule
  - some code from CMSSW, corresponding to a sparse checkout of the required tools.
    - N.B. I tried in the past to add these tools via a submodule, but I was not able to perform a sparse checkout in that case
  - some boost libraries.  I'm not sure how dependencies like this are typically handled in the standalone framework?

The first example I provided reads in an EMP text file, and provides a `BoardData` object, which is essentially a 2D vector of 64 bit words and their CSP flags, arranges by frame and channel.  The other example constructs some dummy data, and writes out a pattern file in EMP format.

### CODE REVIEW

**Comment by jbsauvan** [comment]
Thanks @EmyrClement 
I see `$(CONDA_PREFIX)` is used in the makefile for Boost. This may be more a question for @indra-ehep, but is the standalone framework setup with Conda? 
I suppose that instructions how to install Boost would need to be provided in the README.

**Comment by indra-ehep** [comment]
Thanks @jbsauvan for pointing and @adewit for finding a quick solution. I will update README with updated information. I will check that it compiles in lxplus without break.

**Comment by EmyrClement** [comment]
@adewit - I've also used your workaround in the past, which is fine as long as you have access to `/cvmfs` as you say.  If you want to install in a conda environment as I did, you can install via `conda install conda-forge::boost-cpp`

@jbsauvan @indra-ehep I setup a Conda environment as I couldn't see setup instructions when not running on lxplus, but I assume including a standard setup & environment for everyone to use in the README is the way forward?

**Comment by indra-ehep** [comment]
In lxplus, I found that the EMP extension can be compiled in two ways in addition to what has been mentioned above by @EmyrClement and @adewit 

1) remove $(CONDA_PREFIX)/include from the compilation, the boost is already available in /usr/lib64 and /usr/include, so it will just compile and run
```
[idas@lxplus939 hgcal-tpg-fe]$ make
g++  EMPTools/test.cpp EMPTools/CMSSWCode/L1Trigger/DemonstratorTools/src/* -IEMPTools/CMSSWCode/ -IEMPTools/HLS_arbitrary_Precision_Types/include/  -lboost_iostreams -lz -llzma -o TestEMP.exe
[idas@lxplus939 hgcal-tpg-fe]$ ldd TestEMP.exe 
	linux-vdso.so.1 (0x00007ffde97f0000)
	libboost_iostreams.so.1.75.0 => /lib64/libboost_iostreams.so.1.75.0 (0x00007fb018825000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fb01880b000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007fb0187df000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fb018400000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fb018704000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb0186e9000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb018000000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fb0186d4000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007fb018329000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb01885e000)
[idas@lxplus939 hgcal-tpg-fe]$ ./TestEMP.exe 
Board data name : CMSSW
Data on channel : 81
1101 12375891776014123008
0001 1729382278385303552
0001 281483566645249
0001 30064902150
0001 562959013117956
0001 1125942856515589
Data on channel : 82
1101 12375891776014188544
0001 1729382256910270464
0001 5910978805897216
0001 584944481206272
0001 1731071115360665602
0001 1125934267039744
Data on channel : 83
1101 12375891776014254080
0001 26388279132160
0001 562958543362053
0001 8590196740
0001 844425399894019
0001 1152301070811140
Data on channel : 84
1101 12375891776014319616
0001 1156686232485888
0001 1970350606778369
0001 8590262278
0001 281492559691776
0001 844424930131968
Writing board data (2 channels, 10 frames) to file 'EMPTools/testOutput.txt.gz' (format: EMPv2)
[idas@lxplus939 hgcal-tpg-fe]$
```
2) set CMSSW, e.g. `cmsrel CMSSW_14_0_19`, find boost path defined in `${ROOT_INCLUDE_PATH}` compile and run as
```
Singularity> make
g++  EMPTools/test.cpp EMPTools/CMSSWCode/L1Trigger/DemonstratorTools/src/* -IEMPTools/CMSSWCode/ -IEMPTools/HLS_arbitrary_Precision_Types/include/ -I/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/boost/1.80.0-5ddc09113811f5f52eb43354ccd50ccb/include  -lboost_iostreams -lz -llzma -o TestEMP.exe -L/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/boost/1.80.0-5ddc09113811f5f52eb43354ccd50ccb/lib
Singularity> ldd TestEMP.exe 
	linux-vdso.so.1 (0x00007ffdb7989000)
	libboost_iostreams.so.1.80.0 => /cvmfs/cms.cern.ch/el9_amd64_gcc12/cms/cmssw/CMSSW_14_0_19/external/el9_amd64_gcc12/lib/libboost_iostreams.so.1.80.0 (0x00007fc2d5884000)
	libz.so.1 => /cvmfs/cms.cern.ch/el9_amd64_gcc12/cms/cmssw/CMSSW_14_0_19/external/el9_amd64_gcc12/lib/libz.so.1 (0x00007fc2d5868000)
	liblzma.so.5 => /cvmfs/cms.cern.ch/el9_amd64_gcc12/cms/cmssw/CMSSW_14_0_19/external/el9_amd64_gcc12/lib/liblzma.so.5 (0x00007fc2d583e000)
	libstdc++.so.6 => /cvmfs/cms.cern.ch/el9_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib64/libstdc++.so.6 (0x00007fc2d5600000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc2d5525000)
	libgcc_s.so.1 => /cvmfs/cms.cern.ch/el9_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib64/libgcc_s.so.1 (0x00007fc2d5505000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc2d52fc000)
	libbz2.so.1.0 => /cvmfs/cms.cern.ch/el9_amd64_gcc12/cms/cmssw/CMSSW_14_0_19/external/el9_amd64_gcc12/lib/libbz2.so.1.0 (0x00007fc2d5821000)
	libzstd.so.1 => /cvmfs/cms.cern.ch/el9_amd64_gcc12/cms/cmssw/CMSSW_14_0_19/external/el9_amd64_gcc12/lib/libzstd.so.1 (0x00007fc2d5238000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc2d589e000)
Singularity> which g++
/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/bin/g++
Singularity> ./TestEMP.exe 
Board data name : CMSSW
Data on channel : 81
1101 12375891776014123008
0001 1729382278385303552
0001 281483566645249
0001 30064902150
0001 562959013117956
0001 1125942856515589
Data on channel : 82
1101 12375891776014188544
0001 1729382256910270464
0001 5910978805897216
0001 584944481206272
0001 1731071115360665602
0001 1125934267039744
Data on channel : 83
1101 12375891776014254080
0001 26388279132160
0001 562958543362053
0001 8590196740
0001 844425399894019
0001 1152301070811140
Data on channel : 84
1101 12375891776014319616
0001 1156686232485888
0001 1970350606778369
0001 8590262278
0001 281492559691776
0001 844424930131968
Writing board data (2 channels, 10 frames) to file 'EMPTools/testOutput.txt.gz' (format: EMPv2)
Singularity>
```
The second one close to what @adewit has pointed, in addition we have CMSSW library and paths.

**Pull request merged**
